apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cydwfcaee-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cydwfcaee-java-quarkus-gitops